### ISSUE TITLE
Physics example crashes

### ISSUE THREAD

**Issue by mmcjimsey26** [aclysma/skulpin#111]
Output of `cargo run --example physics --features="winit-app winit-25"`:
```
[2023-01-01T22:37:05Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
[2023-01-01T22:37:05Z DEBUG winit::platform_impl::platform::x11::window] Calculated physical dimensions: 900x600
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::api] Validation mode: Disabled
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::api] Link method for vulkan: Dynamic
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::internal::instance] Found Vulkan version: (1, 3, 235)
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::instance] Available Layers: [
    LayerProperties {
        layer_name: "VK_LAYER_NV_optimus",
        spec_version: 4206816,
        implementation_version: 1,
        description: "NVIDIA Optimus layer",
    },
    LayerProperties {
        layer_name: "VK_LAYER_MESA_device_select",
        spec_version: 4206803,
        implementation_version: 1,
        description: "Linux device selection layer",
    },
    LayerProperties {
        layer_name: "VK_LAYER_LUNARG_api_dump",
        spec_version: 4206823,
        implementation_version: 2,
        description: "LunarG API dump layer",
    },
    LayerProperties {
        layer_name: "VK_LAYER_LUNARG_monitor",
        spec_version: 4206823,
        implementation_version: 1,
        description: "Execution Monitoring Layer",
    },
    LayerProperties {
        layer_name: "VK_LAYER_LUNARG_screenshot",
        spec_version: 4206823,
        implementation_version: 1,
        description: "LunarG image capture layer",
    },
    LayerProperties {
        layer_name: "VK_LAYER_KHRONOS_validation",
        spec_version: 4206823,
        implementation_version: 1,
        description: "Khronos Validation Layer",
    },
    LayerProperties {
        layer_name: "VK_LAYER_INTEL_nullhw",
        spec_version: 4198473,
        implementation_version: 1,
        description: "INTEL NULL HW",
    },
    LayerProperties {
        layer_name: "VK_LAYER_MESA_overlay",
        spec_version: 4206803,
        implementation_version: 1,
        description: "Mesa Overlay layer",
    },
]
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::instance] Available Extensions: [
    ExtensionProperties {
        extension_name: "VK_KHR_device_group_creation",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_display",
        spec_version: 23,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_external_fence_capabilities",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_external_memory_capabilities",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_external_semaphore_capabilities",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_get_display_properties2",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_get_physical_device_properties2",
        spec_version: 2,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_get_surface_capabilities2",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_surface",
        spec_version: 25,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_surface_protected_capabilities",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_wayland_surface",
        spec_version: 6,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_xcb_surface",
        spec_version: 6,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_xlib_surface",
        spec_version: 6,
    },
    ExtensionProperties {
        extension_name: "VK_EXT_acquire_xlib_display",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_EXT_debug_report",
        spec_version: 10,
    },
    ExtensionProperties {
        extension_name: "VK_EXT_debug_utils",
        spec_version: 2,
    },
    ExtensionProperties {
        extension_name: "VK_EXT_direct_mode_display",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_EXT_display_surface_counter",
        spec_version: 1,
    },
    ExtensionProperties {
        extension_name: "VK_KHR_portability_enumeration",
        spec_version: 1,
    },
]
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::instance] Using layers: []
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::instance] Using extensions: ["VK_KHR_surface", "VK_KHR_xlib_surface"]
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::internal::instance] Creating vulkan instance
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] Preferred device types: [DiscreteGpu, IntegratedGpu]
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] Available queue families:
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] Queue Family 0
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] QueueFamilyProperties {
    queue_flags: GRAPHICS | COMPUTE | TRANSFER | SPARSE_BINDING,
    queue_count: 16,
    timestamp_valid_bits: 64,
    min_image_transfer_granularity: Extent3D {
        width: 1,
        height: 1,
        depth: 1,
    },
}
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] Queue Family 1
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] QueueFamilyProperties {
    queue_flags: TRANSFER | SPARSE_BINDING,
    queue_count: 2,
    timestamp_valid_bits: 64,
    min_image_transfer_granularity: Extent3D {
        width: 1,
        height: 1,
        depth: 1,
    },
}
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] Queue Family 2
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] QueueFamilyProperties {
    queue_flags: COMPUTE | TRANSFER | SPARSE_BINDING,
    queue_count: 8,
    timestamp_valid_bits: 64,
    min_image_transfer_granularity: Extent3D {
        width: 1,
        height: 1,
        depth: 1,
    },
}
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] Graphics QF: Some(0)  Compute QF: Some(2)  Transfer QF: Some(1)
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::device_context] Found suitable device 'NVIDIA GeForce GTX 1650 SUPER' API: 1.3.224 DriverVersion: 525.240.704 Score = 200
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Determine required queue counts. Allocation strategies: Graphics: ShareFirstQueueInFamily, Compute: ShareFirstQueueInFamily, Transfer: ShareFirstQueueInFamily
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Queue family indices: VkQueueFamilyIndices { graphics_queue_family_index: 0, compute_queue_family_index: 2, transfer_queue_family_index: 1 }
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Queue families: [QueueFamilyProperties { queue_flags: GRAPHICS | COMPUTE | TRANSFER | SPARSE_BINDING, queue_count: 16, timestamp_valid_bits: 64, min_image_transfer_granularity: Extent3D { width: 1, height: 1, depth: 1 } }, QueueFamilyProperties { queue_flags: TRANSFER | SPARSE_BINDING, queue_count: 2, timestamp_valid_bits: 64, min_image_transfer_granularity: Extent3D { width: 1, height: 1, depth: 1 } }, QueueFamilyProperties { queue_flags: COMPUTE | TRANSFER | SPARSE_BINDING, queue_count: 8, timestamp_valid_bits: 64, min_image_transfer_granularity: Extent3D { width: 1, height: 1, depth: 1 } }]
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Queue counts: {1: 1, 0: 1, 2: 1}
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Graphics queue allocation config: VkQueueAllocationConfig { allocation_strategy: ShareFirstQueueInFamily, queue_family_index: 0, first_queue_index: 0 }
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Compute queue allocation config: VkQueueAllocationConfig { allocation_strategy: ShareFirstQueueInFamily, queue_family_index: 2, first_queue_index: 0 }
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Transfer queue allocation config: VkQueueAllocationConfig { allocation_strategy: ShareFirstQueueInFamily, queue_family_index: 1, first_queue_index: 0 }
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::internal::queue_allocation] Creating queue allocators
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::swapchain] Surface format: SurfaceFormatKHR { format: B8G8R8A8_SRGB, color_space: SRGB_NONLINEAR }
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::swapchain] Available present modes: [FIFO, IMMEDIATE]
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::swapchain] Preferred present modes: [Fifo]
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::swapchain] Present mode: FIFO
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::swapchain] Swapchain extents chosen by surface capabilities (900 600)
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::swapchain] chose swapchain extents Extent2D { width: 900, height: 600 }
[2023-01-01T22:37:05Z INFO  rafx_api::backends::vulkan::swapchain] Extents: Extent2D { width: 900, height: 600 }
[2023-01-01T22:37:05Z DEBUG rafx_api::backends::vulkan::swapchain] Use the graphics queue family to present
[2023-01-01T22:37:05Z INFO  skulpin_renderer::skia_support] Setting up skia backend context with queue family index 0
[2023-01-01T22:37:05Z ERROR skulpin_renderer::skia_support] resolve of vkEnumerateInstanceVersion failed
free(): invalid pointer
[1]    109325 IOT instruction (core dumped)  cargo run --example physics --features="winit-app winit-25"
```
The output of `vulkaninfo | head`, if it helps:
```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.235


Instance Extensions: count = 19
===============================
	VK_EXT_acquire_xlib_display            : extension revision 1
```
Also `gdb` backtrace:
```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff79b96b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7969958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff795353d in __GI_abort () at abort.c:79
#4  0x00007ffff79ad7ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7acc44b "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff79c33dc in malloc_printerr (str=str@entry=0x7ffff7aca0b1 "free(): invalid pointer") at malloc.c:5660
#6  0x00007ffff79c522c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=have_lock@entry=0) at malloc.c:4435
#7  0x00007ffff79c7ba3 in __GI___libc_free (mem=<optimized out>) at malloc.c:3385
#8  0x0000555555dba62b in skia_safe::gpu::backend_surface::{impl#4}::drop (self=0x7fffffff5c28) at src/gpu/backend_surface.rs:179
#9  0x0000555555db6e4b in skia_safe::prelude::{impl#13}::drop<skia_bindings::bindings::GrBackendTexture> (self=0x7fffffff5c28)
    at src/prelude.rs:342
#10 0x0000555555db83ab in core::ptr::drop_in_place<skia_safe::prelude::Handle<skia_bindings::bindings::GrBackendTexture>> ()
    at /rustc/0f529f0f49f4dd404b78e605398531c96f220fc5/library/core/src/ptr/mod.rs:490
#11 0x0000555555d881a3 in core::ptr::drop_in_place<core::option::Option<skia_safe::prelude::Handle<skia_bindings::bindings::GrBackendTexture>>> () at /rustc/0f529f0f49f4dd404b78e605398531c96f220fc5/library/core/src/ptr/mod.rs:490
#12 0x0000555555d8e363 in skulpin_renderer::skia_support::VkSkiaSurface::new (resource_manager=0x7fffffff7480, 
    context=0x7fffffff78d8, extents=...) at skulpin-renderer/src/skia_support.rs:145
#13 0x0000555555d85695 in skulpin_renderer::renderer::{impl#3}::swapchain_created (self=0x7fffffff7af8, 
    _device_context=0x7fffffff7478, swapchain=0x555556e0f128) at skulpin-renderer/src/renderer.rs:117
#14 0x0000555556579a88 in rafx_api::extra::swapchain_helper::RafxSwapchainHelper::new (device_context=0x7fffffff7478, 
    swapchain=..., event_listener=...) at src/extra/swapchain_helper.rs:232
#15 0x0000555555d860e6 in skulpin_renderer::renderer::Renderer::new (window=..., window_size=..., coordinate_system=..., 
    vsync_enabled=true, validation_mode=skulpin_renderer::renderer::ValidationMode::Disabled)
    at skulpin-renderer/src/renderer.rs:195
#16 0x0000555555d855ce in skulpin_renderer::renderer::RendererBuilder::build (self=..., window=..., window_size=...)
    at skulpin-renderer/src/renderer.rs:96
#17 0x0000555555700af7 in skulpin_app_winit::app::App::run<physics::ExampleApp> (app_handler=..., inner_size=..., 
    window_title=..., renderer_builder=...) at skulpin-app-winit/src/app.rs:234
#18 0x0000555555700326 in skulpin_app_winit::app::AppBuilder::run<physics::ExampleApp> (self=..., app_handler=...)
    at skulpin-app-winit/src/app.rs:170
#19 0x00005555556df870 in physics::main () at examples/physics.rs:176
```
https://github.com/aclysma/skulpin/blob/master/skulpin-renderer/src/skia_support.rs#L71-L88 might be relevant?

Thanks for your help.

**Comment by aclysma** [comment]
Thanks for reporting the issue. At this point, I'm not using the crate myself anymore and want to spend my time on other projects. I'm happy to review and accept PRs. Some ideas:
 * Try removing the hack you linked to that forced skia to think only vulkan 1.0 is available (presumably the upstream problems that necessitated that hack have been resolved)
 * Try other versions of upstream skia
 * Try an older vulkan SDK - I've seen new vulkan SDKs cause things to break before (but mainly on mac/moltenvk)

This library hasn't changed at all since Jan 2022 so I think it's more likely something upstream changed - but the right fix may very well be in this library.

**Comment by mmcjimsey26** [comment]
Thanks!
I'll see what I can do and submit a PR if I can fix it.

**Comment by aclysma** [comment]
I think #112 fixes this
